import logging

logger = logging.getLogger(__name__)

class StrategyEngine:
    def __init__(self, total_capital: float = 10000000.0, max_position_pct: float = 0.2):
        """
        Initialize the Strategy Engine with risk parameters.
        :param total_capital: Total portfolio capital available (e.g., 10M KRW)
        :param max_position_pct: Maximum portfolio % allowed per single trade (Risk Parity limit)
        """
        self.total_capital = total_capital
        self.max_position_pct = max_position_pct

    def calculate_kelly_fraction(self, win_prob: float, win_loss_ratio: float = 2.0) -> float:
        """
        Calculate the Kelly Criterion to find the optimal fraction of the bankroll to bet.
        f = p - (1 - p) / b
        where:
        p = probability of a win (derived from LLM confidence)
        b = proportion of the bet gained with a win (e.g., Reward/Risk ratio = 2.0)
        """
        if win_prob <= 0.0 or win_prob >= 1.0:
            return 0.0
            
        q = 1.0 - win_prob
        
        # If the edge is negative (expected value < 0), Kelly is 0
        expected_value = (win_prob * win_loss_ratio) - q
        if expected_value <= 0:
            return 0.0
            
        f_star = win_prob - (q / win_loss_ratio)
        return max(0.0, f_star)

    def position_sizing(self, candidate: dict) -> int:
        """
        Determine the order quantity using Kelly Criterion + Risk Constraints.
        """
        price = candidate.get('price', 0)
        if price <= 0:
            logger.warning(f"Invalid price {price} for candidate. Sizing to 0.")
            return 0
            
        # Extract the confidence score generated by the LLM & Pipeline
        confidence = candidate.get('llm_analysis', {}).get('confidence', 0.5)
        
        # Calculate optimal bet size percentage
        kelly_pct = self.calculate_kelly_fraction(win_prob=confidence)
        
        # Apply Risk Parity constraint (cap the max size)
        allocated_pct = min(kelly_pct, self.max_position_pct)
        
        allocated_capital = self.total_capital * allocated_pct
        
        # Calculate quantity of shares we can buy
        quantity = int(allocated_capital // price)
        
        logger.info(f"[{candidate.get('symbol')}] Sizing: Conf={confidence:.2f} -> Kelly={kelly_pct:.2%} -> Allocated={allocated_pct:.2%} ({allocated_capital:,.0f} KRW) -> Qty={quantity}")
        
        return quantity

    def fuse_signals(self, candidates: list) -> list:
        """
        Iterate through pipeline candidates and apply the final execution logic (like position sizing).
        """
        execution_orders = []
        for candidate in candidates:
            quantity = self.position_sizing(candidate)
            
            if quantity > 0:
                candidate['execution_quantity'] = quantity
                execution_orders.append(candidate)
            else:
                logger.info(f"[{candidate.get('symbol')}] Dropped due to 0 sizing.")
                
        return execution_orders
